import '../styles/globals.css';

import { Space_Grotesk, Manrope } from 'next/font/google';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500'], // Regular = 400, Medium = 500
  variable: '--font-space-grotesk'
});

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '700'], // Regular = 400, Bold = 700
  variable: '--font-manrope'
});

export const metadata = {
  title: 'Raven',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${spaceGrotesk.variable} ${manrope.variable}`}>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
